<a href="https://colab.research.google.com/github/Ardit-K/DataAnalysisPython/blob/main/NumpyLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([0.5, 1, 1.5, 2])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
c = np.array([1, 2, 3, 4], dtype=np.int8)

In [ ]:
c.dtype

dtype('int8')

In [ ]:
s = np.array(['a', 'b', 'c'])

In [ ]:
s.dtype

dtype('<U1')

In [ ]:
s.shape

(3,)

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
A.shape

(2, 3)

In [ ]:
A.ndim

2

In [ ]:
A.size

6

***Indexing and Slicing Arrays***

In [ ]:
A[1,1]

5

In [ ]:
A[:, 0]

array([1, 4])

In [ ]:
A[0, :]

array([1, 2, 3])

In [ ]:
A[0] = np.array([10, 10, 10])

In [ ]:
A

array([[10, 10, 10],
       [ 4,  5,  6]])

In [ ]:
A[1] = 8

In [ ]:
A

array([[10, 10, 10],
       [ 8,  8,  8]])

In [ ]:
A.sum()

54

In [ ]:
A.sum(axis=0)

array([18, 18, 18])

In [ ]:
A.sum(axis=1)

array([30, 24])

***Broadcasting and Vectorized Operations***

In [ ]:
a = np.arange(5)

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a + 20

array([20, 21, 22, 23, 24])

In [ ]:
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
b = np.array([10, 10, 10, 10])

In [ ]:
a + b

array([10, 11, 12, 13])

In [ ]:
a * b

array([ 0, 10, 20, 30])

***Boolean Arrays***

***PANDAS***

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([np.nan, 1, 2, np.nan, 3])

In [ ]:
s = s.fillna(method="bfill")

In [ ]:
print(s)

0    1.0
1    1.0
2    2.0
3    3.0
4    3.0
dtype: float64


In [ ]:
df = pd.DataFrame({
    'Sex': ['M', 'F', 'F', 'D', '?'],
    'Age': [29, 30, 24, 290, 25]
})

In [ ]:
df

Sex  Age
0   M   29
1   F   30
2   F   24
3   D  290
4   ?   25

In [ ]:
df['Sex'].unique()

array(['M', 'F', 'D', '?'], dtype=object)

In [ ]:
df['Sex'].value_counts()

F    2
M    1
D    1
?    1
Name: Sex, dtype: int64

In [ ]:
df['Sex'].replace({"D" : "F", "N" : "M"})

0    M
1    F
2    F
3    F
4    ?
Name: Sex, dtype: object

In [ ]:
df[df['Age'] > 100]

Sex  Age
3   D  290

In [ ]:
df.loc[df['Age']>100, 'Age'] = df.loc[df['Age']>100, 'Age'] / 10

In [ ]:
df

Sex  Age
0   M   29
1   F   30
2   F   24
3   D   29
4   ?   25