<a href="https://colab.research.google.com/github/Ardit-K/DataAnalysisPython/blob/main/Python_testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
list = [0, 1, 2, 3, 4, 5, 6, 7, 8]

mtx = np.array([
    [list[0], list[1], list[2]],
    [list[3], list[4], list[5]],
    [list[6], list[7], list[8]]
])

In [ ]:
mtx.shape

(3, 3)

In [ ]:
mtx

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.max(mtx)

8

In [ ]:
np.max(mtx, axis=0)

array([6, 7, 8])

In [ ]:
np.sum(mtx, axis=0)

array([ 9, 12, 15])

In [ ]:
np.sum(mtx, axis=1)

array([ 3, 12, 21])

In [ ]:
np.sum(mtx)

36

In [7]:
back = np.ones((5,5), dtype=np.int8)
back

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [9]:
mid = np.zeros((3,3), dtype=np.int8)

In [11]:
mid[1,1] = 9
mid

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]], dtype=int8)

In [13]:
back[1:-1, 1:-1] = mid
back

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [16]:
back ** 2

array([[ 1,  1,  1,  1,  1],
       [ 1,  0,  0,  0,  1],
       [ 1,  0, 81,  0,  1],
       [ 1,  0,  0,  0,  1],
       [ 1,  1,  1,  1,  1]], dtype=int8)

In [17]:
back * 4

array([[ 4,  4,  4,  4,  4],
       [ 4,  0,  0,  0,  4],
       [ 4,  0, 36,  0,  4],
       [ 4,  0,  0,  0,  4],
       [ 4,  4,  4,  4,  4]], dtype=int8)

In [18]:
np.sin(back)

array([[0.8413, 0.8413, 0.8413, 0.8413, 0.8413],
       [0.8413, 0.    , 0.    , 0.    , 0.8413],
       [0.8413, 0.    , 0.412 , 0.    , 0.8413],
       [0.8413, 0.    , 0.    , 0.    , 0.8413],
       [0.8413, 0.8413, 0.8413, 0.8413, 0.8413]], dtype=float16)

##### Linear Algebra

In [22]:
# Matrix Multiplication
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [23]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [24]:
#Determinant
c = np.identity(3)
np.linalg.det(c)

1.0

##### Statistics

In [25]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.min(stats)

1

In [27]:
np.max(stats)

6

##### Reorganizing Arrays

In [30]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [32]:
#Vertically stacking
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [35]:
#Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

### Load Data from File

In [ ]:
np.genfromtxt("", delimiter= ',')

### Boolean Masking and Advanced Indexing

In [36]:
a = np.random.randint(0, 100, (10,10))
print(a)

[[ 8 45 36  2 68 42 40 38 10 68]
 [65 58 80 65 95 17 69 89 56 52]
 [64 30 54 50 45 68 87 76 25 18]
 [13  2  0 45 94 36 25 30 40 41]
 [66 61 55 70 64 37 85 73 71 33]
 [42 71  6  8 36 12 17 19 80 93]
 [75 15 19 46 47 14  0 37 49 25]
 [95 39 11 38 26 43 63 61  5 26]
 [68 11 93 70 97 52 57 28 60 55]
 [21 76 46 20 50 16 22  4 99 59]]


In [39]:
a <50

array([[ True,  True,  True,  True, False,  True,  True,  True,  True,
        False],
       [False, False, False, False, False,  True, False, False, False,
        False],
       [False,  True, False, False,  True, False, False, False,  True,
         True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True],
       [False, False, False, False, False,  True, False, False, False,
         True],
       [ True, False,  True,  True,  True,  True,  True,  True, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True, False, False,  True,
         True],
       [False,  True, False, False, False, False, False,  True, False,
        False],
       [ True, False,  True,  True, False,  True,  True,  True, False,
        False]])

In [41]:
a[a < 50]

array([ 8, 45, 36,  2, 42, 40, 38, 10, 17, 30, 45, 25, 18, 13,  2,  0, 45,
       36, 25, 30, 40, 41, 37, 33, 42,  6,  8, 36, 12, 17, 19, 15, 19, 46,
       47, 14,  0, 37, 49, 25, 39, 11, 38, 26, 43,  5, 26, 11, 28, 21, 46,
       20, 16, 22,  4])

In [43]:
# Index with a list in numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(a[[1, 3, 5]])

[2 4 6]
